[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = '0.8.28'

evm_version = 'cancun'
remappings = [
    'forge-std/=lib/forge-std/src/',
    '@openzeppelin/=node_modules/@openzeppelin/',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
